---

# FIXME: something still caused python2 to be installed, which causes the pre_task in the playbook that pip installs
# docker-compose to fail. I apt removed the python2* packages by hand and rerunning the playbook does not appear to
# reinstall them, but this will probably pop up again.
pip_virtualenv_command: /usr/bin/python3 -m virtualenv
certbot_virtualenv_package_name: python3-virtualenv
pip_package: python3-pip

# FIXME: SmartOS auto-formats this ext4 and mounts it, so the task for this fails. Rather than enable the force option
# here and potentially overwrite data on this volume in some future run of this playbook I just ran
# `umount /data && mkfs.xfs -f /dev/vdb` by hand.
filesystems:
  - dev: /dev/vdb
    fstype: xfs

mounts:
  - name: /data
    src: /dev/vdb
    fstype: auto
    mode: "0755"

docker_daemon_option_list:
  - -H fd://
  - --containerd=/run/containerd/containerd.sock
  - --data-root=/data/docker

host_packages:
  - xfsprogs

nginx_flavor: full

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - sentry

certbot_domains:
  - sentry.galaxyproject.org

nginx_conf_http:
  server_names_hash_bucket_size: 128
  proxy_read_timeout: 300
